# site settings for local development

# ignore api dir because it's slow
exclude:
  - api/*
  # copy excludes from _config.yml
  - script
  - test
  - README.md
  - CONTRIBUTING.md
  - Gemfile
  - vendor
